version: '2'

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - ./mysql57/data:/var/lib/mysql
      - ./mysql57/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
